spring:
  application:
    name: release-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/releases
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
