#spring:
#  application:
#    name: release-tracker
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/reltrack
#    username: reltrack
#    password: reltrack
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui
#    display-request-duration: true

spring:
  application:
    name: release-tracker

  profiles:
    default: local

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
